In [1]:
import matplotlib.pyplot as plt
import numpy as np
import numpy.random
import numpy.linalg
import scipy.io
import scipy.stats
import sklearn.metrics

# setup plotting 
from IPython import get_ipython
import psutil
inTerminal = not "IPKernelApp" in get_ipython().config
inJupyterNb = any(filter(lambda x: x.endswith("jupyter-notebook"), psutil.Process().parent().cmdline()))
get_ipython().run_line_magic("matplotlib", "" if inTerminal else "notebook" if inJupyterNb else "widget")
def nextplot():
    if inTerminal:
        plt.clf()     # this clears the current plot
    else:
        plt.figure()  # this creates a new plot 

# Load the data

In [2]:
data = scipy.io.loadmat("data/spamData.mat")
X = data["Xtrain"]
N = X.shape[0]
D = X.shape[1]
Xtest = data["Xtest"]
Ntest = Xtest.shape[0]
y = data["ytrain"].squeeze().astype(int)
ytest = data["ytest"].squeeze().astype(int)

features = np.array(
    [
        "word_freq_make",
        "word_freq_address",
        "word_freq_all",
        "word_freq_3d",
        "word_freq_our",
        "word_freq_over",
        "word_freq_remove",
        "word_freq_internet",
        "word_freq_order",
        "word_freq_mail",
        "word_freq_receive",
        "word_freq_will",
        "word_freq_people",
        "word_freq_report",
        "word_freq_addresses",
        "word_freq_free",
        "word_freq_business",
        "word_freq_email",
        "word_freq_you",
        "word_freq_credit",
        "word_freq_your",
        "word_freq_font",
        "word_freq_000",
        "word_freq_money",
        "word_freq_hp",
        "word_freq_hpl",
        "word_freq_george",
        "word_freq_650",
        "word_freq_lab",
        "word_freq_labs",
        "word_freq_telnet",
        "word_freq_857",
        "word_freq_data",
        "word_freq_415",
        "word_freq_85",
        "word_freq_technology",
        "word_freq_1999",
        "word_freq_parts",
        "word_freq_pm",
        "word_freq_direct",
        "word_freq_cs",
        "word_freq_meeting",
        "word_freq_original",
        "word_freq_project",
        "word_freq_re",
        "word_freq_edu",
        "word_freq_table",
        "word_freq_conference",
        "char_freq_;",
        "char_freq_(",
        "char_freq_[",
        "char_freq_!",
        "char_freq_$",
        "char_freq_#",
        "capital_run_length_average",
        "capital_run_length_longest",
        "capital_run_length_total",
    ]
)

# 1. Dataset Statistics

In [3]:
# look some dataset statistics
scipy.stats.describe(X)

DescribeResult(nobs=3065, minmax=(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1.]), array([4.5400e+00, 1.4280e+01, 5.1000e+00, 4.2810e+01, 9.0900e+00,
       3.5700e+00, 7.2700e+00, 1.1110e+01, 3.3300e+00, 1.8180e+01,
       2.0000e+00, 9.6700e+00, 5.5500e+00, 5.5500e+00, 2.8600e+00,
       1.0160e+01, 7.1400e+00, 9.0900e+00, 1.8750e+01, 6.3200e+00,
       1.1110e+01, 1.7100e+01, 5.4500e+00, 9.0900e+00, 2.0000e+01,
       1.4280e+01, 3.3330e+01, 4.7600e+00, 1.4280e+01, 4.7600e+00,
       4.7600e+00, 4.7600e+00, 1.8180e+01, 4.7600e+00, 2.0000e+01,
       7.6900e+00, 6.8900e+00, 7.4000e+00, 9.7500e+00, 4.7600e+00,
       7.1400e+00, 1.4280e+01, 3.5700e+00, 2.0000e+01, 2.1420e+01,
       1.6700e+01, 2.1200e+00, 1.0000e+01, 4.3850e+00, 9.7520e+00,
       4.0810e+00, 3.2478e+01, 6.0030e

In [4]:
scipy.stats.describe(y)

DescribeResult(nobs=3065, minmax=(0, 1), mean=0.39738988580750406, variance=0.23954932085067238, skewness=0.41936632478193103, kurtosis=-1.824131885638896)

In [5]:
# plot the distribution of all features
nextplot()
densities = [scipy.stats.gaussian_kde(X[:, j]) for j in range(D)]
xs = np.linspace(0, np.max(X), 200)
for j in range(D):
    plt.plot(xs, densities[j](xs), label=j)
plt.legend(ncol=5)

<IPython.core.display.Javascript object>

In [6]:
# this plots is not really helpful; go now explore further
# YOUR CODE HERE
nextplot()
densities = [scipy.stats.gaussian_kde(X[:, j]) for j in range(D)]
xs = np.linspace(-.3,.3)
for j in range(D):
    plt.plot(xs, densities[j](xs), label=j)
plt.legend(ncol=5)

<IPython.core.display.Javascript object>

In [7]:
import pandas as pd
df = pd.DataFrame(X)
print(df.describe())

                0            1            2            3            4   \
count  3065.000000  3065.000000  3065.000000  3065.000000  3065.000000   
mean      0.110819     0.228486     0.274153     0.062969     0.317788   
std       0.327252     1.373834     0.484063     1.334772     0.663570   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.410000     0.000000     0.390000   
max       4.540000    14.280000     5.100000    42.810000     9.090000   

                5            6            7            8            9   ...  \
count  3065.000000  3065.000000  3065.000000  3065.000000  3065.000000  ...   
mean      0.095755     0.113546     0.107217     0.088923     0.241719  ...   
std       0.260613     0.373958     0.414731     0.264054     0.685420  ...   
min       0.00000

In [8]:
# Let's compute z-scores; create two new variables Xz and Xtestz.
Xz = (X - np.mean(X,axis=0))/np.std(X,axis=0)
Xtestz = (Xtest - np.mean(X,axis=0))/np.std(X,axis=0)

In [9]:
# Let's check. Xz and Xtestz refer to the normalized datasets just created. We
# will use them throughout.
np.mean(Xz, axis=0)  # should be all 0
np.var(Xz, axis=0)  # should be all 1
np.mean(Xtestz, axis=0)  # what do you get here?
np.var(Xtestz, axis=0)

np.sum(Xz ** 3)  # should be: 1925261.15

1925261.1560010156

In [10]:
# Explore the normalized data
# YOUR CODE HERE
nextplot()
densities = [scipy.stats.gaussian_kde(Xz[:, j]) for j in range(D)]
xsz = np.linspace(-5,5)
for j in range(D):
    plt.plot(xsz, densities[j](xsz), label=j)

<IPython.core.display.Javascript object>

# 2. Maximum Likelihood Estimation

In [11]:
import numpy as np
import matplotlib.pyplot as plt
def sigmoid(x) :
    return 1/(1+np.exp(-x))

x = np.arange(-5.0,5.0,0.1)
y1 = sigmoid(x+0.5)
y2 = sigmoid(x+1)
y3 = sigmoid(x+1.5)

nextplot()
plt.plot(x,y1,'r', linestyle = '--') #x+0.5
plt.plot(x,y2,'g') #x+1
plt.plot(x,y3,'b', linestyle = '--') #x+1.5
plt.plot([0,0],[1.0,0.0],':') #add dotted line in the middle
plt.title('Sigmoid Function')
plt.show()
plt.savefig('Figure2.1.png')

<IPython.core.display.Javascript object>

## Helper functions

In [12]:
def logsumexp(x):
    """Computes log(sum(exp(x)).

    Uses offset trick to reduce risk of numeric over- or underflow. When x is a
    1D ndarray, computes logsumexp of its entries. When x is a 2D ndarray,
    computes logsumexp of each column.

    Keyword arguments:
    x : a 1D or 2D ndarray
    """
    offset = np.max(x, axis=0)
    return offset + np.log(np.sum(np.exp(x - offset), axis=0))

In [13]:
# Define the logistic function. Make sure it operates on both scalars
# and vectors.
def sigma(x):
    # YOUR CODE HERE
    logistic_function = 1/(1+np.exp(-x))
    return logistic_function

In [14]:
# this should give:
# [0.5, array([0.26894142, 0.5, 0.73105858])]
[sigma(0), sigma(np.array([-1, 0, 1]))]

[0.5, array([0.26894142, 0.5       , 0.73105858])]

In [15]:
# Define the logarithm of the logistic function. Make sure it operates on both
# scalars and vectors. Perhaps helpful: isinstance(x, np.ndarray).
def logsigma(x):
    # YOUR CODE HERE
    log_logistic_function = np.log(sigma(x))
    return log_logistic_function

In [16]:
# this should give:
# [-0.69314718055994529, array([-1.31326169, -0.69314718, -0.31326169])]
[logsigma(0), logsigma(np.array([-1, 0, 1]))]

[-0.6931471805599453, array([-1.31326169, -0.69314718, -0.31326169])]

## 2b Log-likelihood and gradient

In [17]:
def l(y, X, w):
    """Log-likelihood of the logistic regression model.

    Parameters
    ----------
    y : ndarray of shape (N,)
        Binary labels (either 0 or 1).
    X : ndarray of shape (N,D)
        Design matrix.
    w : ndarray of shape (D,)
        Weight vector.
    """
    # YOUR CODE HERE
    z = np.dot(X,w)
    return np.sum(y*z - np.log(1+np.exp(z)))

In [18]:
# this should give:
# -47066.641667825766
l(y, Xz, np.linspace(-5, 5, D))

-47066.64166782577

In [19]:
def dl(y, X, w):
    """Gradient of the log-likelihood of the logistic regression model.

    Parameters
    ----------
    y : ndarray of shape (N,)
        Binary labels (either 0 or 1).
    X : ndarray of shape (N,D)
        Design matrix.
    w : ndarray of shape (D,)
        Weight vector.

    Returns
    -------
    ndarray of shape (D,)
    """
    # YOUR CODE HERE
    z = np.dot(X,w)
    prediction = sigma(z)
    errors = y - prediction
    gradients = np.dot(X.T,errors)
    return gradients

In [20]:
# this should give:
# array([  551.33985842,   143.84116318,   841.83373606,   156.87237578,
#          802.61217579,   795.96202907,   920.69045803,   621.96516752,
#          659.18724769,   470.81259805,   771.32406968,   352.40325626,
#          455.66972482,   234.36600888,   562.45454038,   864.83981264,
#          787.19723703,   649.48042176,   902.6478154 ,   544.00539886,
#         1174.78638035,   120.3598967 ,   839.61141672,   633.30453444,
#         -706.66815087,  -630.2039816 ,  -569.3451386 ,  -527.50996698,
#         -359.53701083,  -476.64334832,  -411.60620464,  -375.11950586,
#         -345.37195689,  -376.22044258,  -407.31761977,  -456.23251936,
#         -596.86960184,  -107.97072355,  -394.82170044,  -229.18125598,
#         -288.46356547,  -362.13402385,  -450.87896465,  -277.03932676,
#         -414.99293368,  -452.28771693,  -167.54649092,  -270.9043748 ,
#         -252.20140951,  -357.72497343,  -259.12468742,   418.35938483,
#          604.54173228,    43.10390907,   152.24258478,   378.16731033,
#          416.12032881])
dl(y, Xz, np.linspace(-5, 5, D))

array([ 551.33985842,  143.84116318,  841.83373606,  156.87237578,
        802.61217579,  795.96202907,  920.69045803,  621.96516752,
        659.18724769,  470.81259805,  771.32406968,  352.40325626,
        455.66972482,  234.36600888,  562.45454038,  864.83981264,
        787.19723703,  649.48042176,  902.6478154 ,  544.00539886,
       1174.78638035,  120.3598967 ,  839.61141672,  633.30453444,
       -706.66815087, -630.2039816 , -569.3451386 , -527.50996698,
       -359.53701083, -476.64334832, -411.60620464, -375.11950586,
       -345.37195689, -376.22044258, -407.31761977, -456.23251936,
       -596.86960184, -107.97072355, -394.82170044, -229.18125598,
       -288.46356547, -362.13402385, -450.87896465, -277.03932676,
       -414.99293368, -452.28771693, -167.54649092, -270.9043748 ,
       -252.20140951, -357.72497343, -259.12468742,  418.35938483,
        604.54173228,   43.10390907,  152.24258478,  378.16731033,
        416.12032881])

## 2c Gradient descent

In [21]:
# you don't need to modify this function
def optimize(obj_up, theta0, nepochs=50, eps0=0.01, verbose=True):
    """Iteratively minimize a function.

    We use it here to run either gradient descent or stochastic gradient
    descent, using arbitrarly optimization criteria.

    Parameters
    ----------
    obj_up  : a tuple of form (f, update) containing two functions f and update.
              f(theta) computes the value of the objective function.
              update(theta,eps) performs an epoch of parameter update with step size
              eps and returns the result.
    theta0  : ndarray of shape (D,)
              Initial parameter vector.
    nepochs : int
              How many epochs (calls to update) to run.
    eps0    : float
              Initial step size.
    verbose : boolean
              Whether to print progress information.

    Returns
    -------
    A triple consisting of the fitted parameter vector, the values of the
    objective function after every epoch, and the step sizes that were used.
    """

    f, update = obj_up

    # initialize results
    theta = theta0
    values = np.zeros(nepochs + 1)
    eps = np.zeros(nepochs + 1)
    values[0] = f(theta0)
    eps[0] = eps0

    # now run the update function nepochs times
    for epoch in range(nepochs):
        if verbose:
            print(
                "Epoch {:3d}: f={:10.3f}, eps={:10.9f}".format(
                    epoch, values[epoch], eps[epoch]
                )
            )
        theta = update(theta, eps[epoch])

        # we use the bold driver heuristic
        values[epoch + 1] = f(theta)
        if values[epoch] < values[epoch + 1]:
            eps[epoch + 1] = eps[epoch] / 2.0
        else:
            eps[epoch + 1] = eps[epoch] * 1.05

    # all done
    if verbose:
        print("Result after {} epochs: f={}".format(nepochs, values[-1]))
    return theta, values, eps

In [22]:
# define the objective and update function for one gradient-descent epoch for
# fitting an MLE estimate of logistic regression with gradient descent (should
# return a tuple of two functions; see optimize)
def gd(y, X):
    def objective(w):
        # YOUR CODE HERE
        p_i1 = logsigma(np.dot(X,w))
        p_i0 = logsigma(-np.dot(X,w))
        objective = -np.sum(y*p_i1 + (1-y)*p_i0)
        return objective
    
    def update(w, eps):
        # YOUR CODE HERE
        gradients = dl(y,X,w)
        w += eps * gradients
        return w
    
    return (objective, update)

In [23]:
# this should give
# [47066.641667825766,
#  array([  4.13777838e+01,  -1.56745627e+01,   5.75882538e+01,
#           1.14225143e+01,   5.54249703e+01,   5.99229049e+01,
#           7.11220141e+01,   4.84761728e+01,   5.78067289e+01,
#           4.54794720e+01,   7.14638492e+01,   1.51369386e+01,
#           3.36375739e+01,   2.15061217e+01,   5.78014255e+01,
#           6.72743066e+01,   7.00829312e+01,   5.29328088e+01,
#           6.16042473e+01,   5.50018510e+01,   8.94624817e+01,
#           2.74784480e+01,   8.51763599e+01,   5.60363965e+01,
#          -2.55865589e+01,  -1.53788213e+01,  -4.67015412e+01,
#          -2.50356570e+00,  -3.85357592e+00,  -2.21819155e+00,
#           3.32098671e+00,   3.86933390e+00,  -2.00309898e+01,
#           3.84684492e+00,  -2.19847927e-01,  -1.29775457e+00,
#          -1.28374302e+01,  -2.78303173e+00,  -5.61671182e+00,
#           1.73657121e+01,  -6.81197570e+00,  -1.20249002e+01,
#           2.65789491e+00,  -1.39557852e+01,  -2.01135653e+01,
#          -2.72134051e+01,  -9.45952961e-01,  -1.02239111e+01,
#           1.52794293e-04,  -5.18938123e-01,  -3.19717561e+00,
#           4.62953437e+01,   7.87893022e+01,   1.88618651e+01,
#           2.85195027e+01,   5.04698358e+01,   6.41240689e+01])
f, update = gd(y, Xz)
[f(np.linspace(-5, 5, D)), update(np.linspace(-5, -5, D), 0.1)]

[47066.64166782577,
 array([ 4.13777838e+01, -1.56745627e+01,  5.75882538e+01,  1.14225143e+01,
         5.54249703e+01,  5.99229049e+01,  7.11220141e+01,  4.84761728e+01,
         5.78067289e+01,  4.54794720e+01,  7.14638492e+01,  1.51369386e+01,
         3.36375739e+01,  2.15061217e+01,  5.78014255e+01,  6.72743066e+01,
         7.00829312e+01,  5.29328088e+01,  6.16042473e+01,  5.50018510e+01,
         8.94624817e+01,  2.74784480e+01,  8.51763599e+01,  5.60363965e+01,
        -2.55865589e+01, -1.53788213e+01, -4.67015412e+01, -2.50356570e+00,
        -3.85357592e+00, -2.21819155e+00,  3.32098671e+00,  3.86933390e+00,
        -2.00309898e+01,  3.84684492e+00, -2.19847927e-01, -1.29775457e+00,
        -1.28374302e+01, -2.78303173e+00, -5.61671182e+00,  1.73657121e+01,
        -6.81197570e+00, -1.20249002e+01,  2.65789491e+00, -1.39557852e+01,
        -2.01135653e+01, -2.72134051e+01, -9.45952961e-01, -1.02239111e+01,
         1.52794293e-04, -5.18938123e-01, -3.19717561e+00,  4.629534

In [24]:
# you can run gradient descent!
numpy.random.seed(0)
w0 = np.random.normal(size=D)
wz_gd, vz_gd, ez_gd = optimize(gd(y, Xz), w0, nepochs=500)

Epoch   0: f=  6636.208, eps=0.010000000
Epoch   1: f=  4216.957, eps=0.010500000
Epoch   2: f=  2657.519, eps=0.011025000
Epoch   3: f=  1926.135, eps=0.011576250
Epoch   4: f=  1449.495, eps=0.012155063
Epoch   5: f=  1207.529, eps=0.012762816
Epoch   6: f=  1052.489, eps=0.013400956
Epoch   7: f=   957.275, eps=0.014071004
Epoch   8: f=   899.610, eps=0.014774554
Epoch   9: f=   882.904, eps=0.015513282
Epoch  10: f=  1017.083, eps=0.007756641
Epoch  11: f=   840.760, eps=0.008144473
Epoch  12: f=   805.649, eps=0.008551697
Epoch  13: f=   822.108, eps=0.004275848
Epoch  14: f=   746.377, eps=0.004489641
Epoch  15: f=   735.803, eps=0.004714123
Epoch  16: f=   729.780, eps=0.004949829
Epoch  17: f=   724.467, eps=0.005197320
Epoch  18: f=   719.408, eps=0.005457186
Epoch  19: f=   714.564, eps=0.005730046
Epoch  20: f=   709.932, eps=0.006016548
Epoch  21: f=   705.514, eps=0.006317375
Epoch  22: f=   701.321, eps=0.006633244
Epoch  23: f=   697.373, eps=0.006964906
Epoch  24: f=   

Epoch 435: f=   656.504, eps=0.007464239
Epoch 436: f=   656.482, eps=0.007837451
Epoch 437: f=   656.459, eps=0.008229324
Epoch 438: f=   656.435, eps=0.008640790
Epoch 439: f=   656.410, eps=0.009072829
Epoch 440: f=   656.388, eps=0.009526471
Epoch 441: f=   656.406, eps=0.004763235
Epoch 442: f=   656.387, eps=0.005001397
Epoch 443: f=   656.379, eps=0.005251467
Epoch 444: f=   656.381, eps=0.002625734
Epoch 445: f=   656.303, eps=0.002757020
Epoch 446: f=   656.295, eps=0.002894871
Epoch 447: f=   656.286, eps=0.003039615
Epoch 448: f=   656.277, eps=0.003191596
Epoch 449: f=   656.268, eps=0.003351175
Epoch 450: f=   656.258, eps=0.003518734
Epoch 451: f=   656.248, eps=0.003694671
Epoch 452: f=   656.237, eps=0.003879404
Epoch 453: f=   656.226, eps=0.004073375
Epoch 454: f=   656.214, eps=0.004277043
Epoch 455: f=   656.202, eps=0.004490895
Epoch 456: f=   656.189, eps=0.004715440
Epoch 457: f=   656.175, eps=0.004951212
Epoch 458: f=   656.161, eps=0.005198773
Epoch 459: f=   

In [25]:
# look at how gradient descent made progess
# YOUR CODE HERE
nextplot()
plt.plot(range(501),vz_gd)
plt.show()

<IPython.core.display.Javascript object>

## 2d Stochastic gradient descent

In [26]:
def sgdepoch(y, X, w, eps):
    """Run one SGD epoch and return the updated weight vector. """
    # Run N stochastic gradient steps (without replacement). Do not rescale each
    # step by factor N (i.e., proceed differently than in the lecture slides).
    # YOUR CODE HERE
    # np.random.rand(2022)
    # np.random.shuffle(X)
    # np.random.shuffle(y)
    index_list = list(range(X.shape[0]))
    np.random.shuffle(index_list)
    for i in index_list :
        gradient = dl(y[i],X[i],w)
        w += eps * gradient
        return w

In [27]:
# when you run this multiple times, with 50% probability you should get the
# following result (there is one other result which is very close):
# array([ -3.43689655e+02,  -1.71161311e+02,  -5.71093536e+02,
#         -5.16478220e+01,   4.66294348e+02,  -3.71589878e+02,
#          5.21493183e+02,   1.25699230e+03,   8.33804130e+02,
#          5.63185399e+02,   1.32761302e+03,  -2.64104011e+02,
#          7.10693307e+02,  -1.75497331e+02,  -1.94174427e+02,
#          1.11641507e+02,  -3.30817509e+02,  -3.46754913e+02,
#          8.48722111e+02,  -1.89136304e+02,  -4.25693844e+02,
#         -1.23084189e+02,  -2.95894797e+02,  -2.35789333e+02,
#         -3.38695243e+02,  -3.05642830e+02,  -2.28975383e+02,
#         -2.38075137e+02,  -1.66702530e+02,  -2.27341599e+02,
#         -1.77575620e+02,  -1.49093855e+02,  -1.70028859e+02,
#         -1.50243833e+02,  -1.82986008e+02,  -2.41143708e+02,
#         -3.31047159e+02,  -5.79991185e+01,  -1.98477863e+02,
#         -1.91264948e+02,  -1.17371919e+02,  -1.66953779e+02,
#         -2.01472565e+02,  -1.23330949e+02,  -3.00857740e+02,
#         -1.95853348e+02,  -7.44868073e+01,  -1.11172370e+02,
#         -1.57618226e+02,  -1.25729512e+00,  -1.45536466e+02,
#         -1.43362438e+02,  -3.00429708e+02,  -9.84391082e+01,
#         -4.54152047e+01,  -5.26492232e+01,  -1.45175427e+02])
sgdepoch(y[1:3], Xz[1:3, :], np.linspace(-5, 5, D), 1000)

array([-3.43689655e+02, -1.71161311e+02, -5.71093536e+02, -5.16478220e+01,
        4.66294348e+02, -3.71589878e+02,  5.21493183e+02,  1.25699230e+03,
        8.33804130e+02,  5.63185399e+02,  1.32761302e+03, -2.64104011e+02,
        7.10693307e+02, -1.75497331e+02, -1.94174427e+02,  1.11641507e+02,
       -3.30817509e+02, -3.46754913e+02,  8.48722111e+02, -1.89136304e+02,
       -4.25693844e+02, -1.23084189e+02, -2.95894797e+02, -2.35789333e+02,
       -3.38695243e+02, -3.05642830e+02, -2.28975383e+02, -2.38075137e+02,
       -1.66702530e+02, -2.27341599e+02, -1.77575620e+02, -1.49093855e+02,
       -1.70028859e+02, -1.50243833e+02, -1.82986008e+02, -2.41143708e+02,
       -3.31047159e+02, -5.79991185e+01, -1.98477863e+02, -1.91264948e+02,
       -1.17371919e+02, -1.66953779e+02, -2.01472565e+02, -1.23330949e+02,
       -3.00857740e+02, -1.95853348e+02, -7.44868073e+01, -1.11172370e+02,
       -1.57618226e+02, -1.25729512e+00, -1.45536466e+02, -1.43362438e+02,
       -3.00429708e+02, -

In [28]:
# define the objective and update function for one gradient-descent epoch for
# fitting an MLE estimate of logistic regression with stochastic gradient descent
# (should return a tuple of two functions; see optimize)
def sgd(y, X):
    def objective(w):
        # YOUR CODE HERE   
        p_i0 = logsigma(-np.dot(X,w))
        p_i1 = logsigma(np.dot(X,w))
        objective = -np.sum(y*p_i1 + (1-y)*p_i0)
        return objective
    
    def update(w, eps):
        return sgdepoch(y, X, w, eps)

    return (objective, update)

In [29]:
# with 50% probability, you should get:
# [40.864973045695081,
#  array([ -3.43689655e+02,  -1.71161311e+02,  -5.71093536e+02,
#          -5.16478220e+01,   4.66294348e+02,  -3.71589878e+02,
#           5.21493183e+02,   1.25699230e+03,   8.33804130e+02,
#           5.63185399e+02,   1.32761302e+03,  -2.64104011e+02,
#           7.10693307e+02,  -1.75497331e+02,  -1.94174427e+02,
#           1.11641507e+02,  -3.30817509e+02,  -3.46754913e+02,
#           8.48722111e+02,  -1.89136304e+02,  -4.25693844e+02,
#          -1.23084189e+02,  -2.95894797e+02,  -2.35789333e+02,
#          -3.38695243e+02,  -3.05642830e+02,  -2.28975383e+02,
#          -2.38075137e+02,  -1.66702530e+02,  -2.27341599e+02,
#          -1.77575620e+02,  -1.49093855e+02,  -1.70028859e+02,
#          -1.50243833e+02,  -1.82986008e+02,  -2.41143708e+02,
#          -3.31047159e+02,  -5.79991185e+01,  -1.98477863e+02,
#          -1.91264948e+02,  -1.17371919e+02,  -1.66953779e+02,
#          -2.01472565e+02,  -1.23330949e+02,  -3.00857740e+02,
#          -1.95853348e+02,  -7.44868073e+01,  -1.11172370e+02,
#          -1.57618226e+02,  -1.25729512e+00,  -1.45536466e+02,
#          -1.43362438e+02,  -3.00429708e+02,  -9.84391082e+01,
#          -4.54152047e+01,  -5.26492232e+01,  -1.45175427e+02])]
f, update = sgd(y[1:3], Xz[1:3, :])
[f(np.linspace(-5, 5, D)), update(np.linspace(-5, 5, D), 1000)]

[40.864973045695095,
 array([-3.43689655e+02, -1.71161311e+02, -5.71093536e+02, -5.16478220e+01,
         4.66294348e+02, -3.71589878e+02,  5.21493183e+02,  1.25699230e+03,
         8.33804130e+02,  5.63185399e+02,  1.32761302e+03, -2.64104011e+02,
         7.10693307e+02, -1.75497331e+02, -1.94174427e+02,  1.11641507e+02,
        -3.30817509e+02, -3.46754913e+02,  8.48722111e+02, -1.89136304e+02,
        -4.25693844e+02, -1.23084189e+02, -2.95894797e+02, -2.35789333e+02,
        -3.38695243e+02, -3.05642830e+02, -2.28975383e+02, -2.38075137e+02,
        -1.66702530e+02, -2.27341599e+02, -1.77575620e+02, -1.49093855e+02,
        -1.70028859e+02, -1.50243833e+02, -1.82986008e+02, -2.41143708e+02,
        -3.31047159e+02, -5.79991185e+01, -1.98477863e+02, -1.91264948e+02,
        -1.17371919e+02, -1.66953779e+02, -2.01472565e+02, -1.23330949e+02,
        -3.00857740e+02, -1.95853348e+02, -7.44868073e+01, -1.11172370e+02,
        -1.57618226e+02, -1.25729512e+00, -1.45536466e+02, -1.43362

In [30]:
# you can run stochastic gradient descent!
wz_sgd, vz_sgd, ez_sgd = optimize(sgd(y, Xz), w0, nepochs=500)

Epoch   0: f=   655.413, eps=0.010000000
Epoch   1: f=   655.413, eps=0.010500000
Epoch   2: f=   655.413, eps=0.011025000
Epoch   3: f=   655.413, eps=0.005512500
Epoch   4: f=   655.414, eps=0.002756250
Epoch   5: f=   655.439, eps=0.001378125
Epoch   6: f=   655.439, eps=0.000689063
Epoch   7: f=   655.439, eps=0.000344531
Epoch   8: f=   655.439, eps=0.000172266
Epoch   9: f=   655.439, eps=0.000086133
Epoch  10: f=   655.439, eps=0.000043066
Epoch  11: f=   655.439, eps=0.000045220
Epoch  12: f=   655.439, eps=0.000022610
Epoch  13: f=   655.439, eps=0.000023740
Epoch  14: f=   655.439, eps=0.000011870
Epoch  15: f=   655.439, eps=0.000005935
Epoch  16: f=   655.439, eps=0.000006232
Epoch  17: f=   655.439, eps=0.000006543
Epoch  18: f=   655.439, eps=0.000003272
Epoch  19: f=   655.439, eps=0.000001636
Epoch  20: f=   655.439, eps=0.000000818
Epoch  21: f=   655.439, eps=0.000000409
Epoch  22: f=   655.439, eps=0.000000429
Epoch  23: f=   655.439, eps=0.000000215
Epoch  24: f=   

Epoch 326: f=   655.439, eps=0.000000000
Epoch 327: f=   655.439, eps=0.000000000
Epoch 328: f=   655.439, eps=0.000000000
Epoch 329: f=   655.439, eps=0.000000000
Epoch 330: f=   655.439, eps=0.000000000
Epoch 331: f=   655.439, eps=0.000000000
Epoch 332: f=   655.439, eps=0.000000000
Epoch 333: f=   655.439, eps=0.000000000
Epoch 334: f=   655.439, eps=0.000000000
Epoch 335: f=   655.439, eps=0.000000000
Epoch 336: f=   655.439, eps=0.000000000
Epoch 337: f=   655.439, eps=0.000000000
Epoch 338: f=   655.439, eps=0.000000000
Epoch 339: f=   655.439, eps=0.000000000
Epoch 340: f=   655.439, eps=0.000000000
Epoch 341: f=   655.439, eps=0.000000000
Epoch 342: f=   655.439, eps=0.000000000
Epoch 343: f=   655.439, eps=0.000000000
Epoch 344: f=   655.439, eps=0.000000000
Epoch 345: f=   655.439, eps=0.000000000
Epoch 346: f=   655.439, eps=0.000000000
Epoch 347: f=   655.439, eps=0.000000000
Epoch 348: f=   655.439, eps=0.000000000
Epoch 349: f=   655.439, eps=0.000000000
Epoch 350: f=   

## 2e Compare GD and SGD

In [31]:
# YOUR CODE HERE
nextplot()
plt.plot(range(501),vz_gd,label='Gradient Descent')
plt.plot(range(501),vz_sgd,label='Stochastic Gradient Descent')
plt.legend()
plt.show()
plt.savefig('Figure2.2.png')

<IPython.core.display.Javascript object>

In [32]:
# YOUR CODE HERE
nextplot()
plt.plot(range(501),vz_gd,label='adj Gradient Descent')
plt.plot(range(501),vz_sgd,label='adj Stochastic Gradient Descent')
plt.xlim(0,50)
plt.legend()
plt.show()
plt.savefig('Figure2.3.png')

<IPython.core.display.Javascript object>

# 3 Prediction

In [33]:
def predict(Xtest, w):
    """Returns vector of predicted confidence values for logistic regression with
weight vector w."""
    # YOUR CODE HERE
    z = np.dot(Xtest, w)
    prediction = sigma(z)
    return prediction

def classify(Xtest, w):
    """Returns 0/1 vector of predicted class labels for logistic regression with
weight vector w."""
    # YOUR CODE HERE
    return np.where(predict(Xtest,w) > 0.5 , 1, 0)

In [34]:
# Example: confusion matrix
yhat = predict(Xtestz, wz_gd)
ypred = classify(Xtestz, wz_gd)
print(sklearn.metrics.confusion_matrix(ytest, ypred))  # true x predicted

[[887  54]
 [ 71 524]]


In [35]:
# Example: classification report
print(sklearn.metrics.classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93       941
           1       0.91      0.88      0.89       595

    accuracy                           0.92      1536
   macro avg       0.92      0.91      0.91      1536
weighted avg       0.92      0.92      0.92      1536



In [36]:
# Example: precision-recall curve (with annotated thresholds)
nextplot()
precision, recall, thresholds = sklearn.metrics.precision_recall_curve(ytest, yhat)
plt.plot(recall, precision)
for x in np.linspace(0, 1, 10, endpoint=False):
    index = int(x * (precision.size - 1))
    plt.text(recall[index], precision[index], "{:3.2f}".format(thresholds[index]))
plt.xlabel("Recall")
plt.ylabel("Precision")

<IPython.core.display.Javascript object>

Text(0, 0.5, 'Precision')

In [37]:
# Explore which features are considered important
# YOUR CODE HERE
nextplot()
plt.plot(range(len(wz_gd)),wz_gd,'-o')
plt.xlabel('Index Feature')
plt.ylabel('Weight')
plt.savefig('Figure2.4.png')

<IPython.core.display.Javascript object>

In [38]:
max(wz_gd)
np.argmax(wz_gd)
min(wz_gd)
np.argmin(wz_gd)

24

# 4 Maximum Aposteriori Estimation

## 4a Gradient Descent

In [39]:
def l_l2(y, X, w, lambda_):
    """Log-density of posterior of logistic regression with weights w and L2
regularization parameter lambda_"""
    # YOUR CODE HERE
    pos_logistic_regression = l(y,X,w) - (lambda_/2)*(np.dot(w,w))
    #(np.linalg.norm(w,ord=2))
    return pos_logistic_regression

In [40]:
# this should give:
# [-47066.641667825766, -47312.623810682911]
[l_l2(y, Xz, np.linspace(-5, 5, D), 0), l_l2(y, Xz, np.linspace(-5, 5, D), 1)]

[-47066.64166782577, -47312.62381068291]

In [41]:
def dl_l2(y, X, w, lambda_):
    """Gradient of log-density of posterior of logistic regression with weights w
and L2 regularization parameter lambda_."""
    # YOUR CODE HERE
    gradient = dl(y,X,w) - (lambda_)*w
    return gradient

In [42]:
# this should give:
# [array([  551.33985842,   143.84116318,   841.83373606,   156.87237578,
#           802.61217579,   795.96202907,   920.69045803,   621.96516752,
#           659.18724769,   470.81259805,   771.32406968,   352.40325626,
#           455.66972482,   234.36600888,   562.45454038,   864.83981264,
#           787.19723703,   649.48042176,   902.6478154 ,   544.00539886,
#          1174.78638035,   120.3598967 ,   839.61141672,   633.30453444,
#          -706.66815087,  -630.2039816 ,  -569.3451386 ,  -527.50996698,
#          -359.53701083,  -476.64334832,  -411.60620464,  -375.11950586,
#          -345.37195689,  -376.22044258,  -407.31761977,  -456.23251936,
#          -596.86960184,  -107.97072355,  -394.82170044,  -229.18125598,
#          -288.46356547,  -362.13402385,  -450.87896465,  -277.03932676,
#          -414.99293368,  -452.28771693,  -167.54649092,  -270.9043748 ,
#          -252.20140951,  -357.72497343,  -259.12468742,   418.35938483,
#           604.54173228,    43.10390907,   152.24258478,   378.16731033,
#           416.12032881]),
#  array([  556.33985842,   148.66259175,   846.4765932 ,   161.33666149,
#           806.89789007,   800.06917193,   924.61902946,   625.71516752,
#           662.75867626,   474.20545519,   774.5383554 ,   355.43897054,
#           458.52686767,   237.04458031,   564.95454038,   867.16124121,
#           789.34009417,   651.44470748,   904.43352968,   545.61254171,
#          1176.21495178,   121.6098967 ,   840.68284529,   634.19739158,
#          -705.95386516,  -629.66826731,  -568.98799574,  -527.33139555,
#          -359.53701083,  -476.82191975,  -411.9633475 ,  -375.65522015,
#          -346.08624261,  -377.11329972,  -408.38904835,  -457.48251936,
#          -598.29817327,  -109.57786641,  -396.60741472,  -231.14554169,
#          -290.60642261,  -364.45545242,  -453.37896465,  -279.71789819,
#          -417.85007654,  -455.32343122,  -170.76077664,  -274.29723194,
#          -255.77283808,  -361.47497343,  -263.05325885,   414.25224198,
#           600.25601799,    38.63962335,   147.59972763,   373.34588176,
#           411.12032881])]
[dl_l2(y, Xz, np.linspace(-5, 5, D), 0), dl_l2(y, Xz, np.linspace(-5, 5, D), 1)]

[array([ 551.33985842,  143.84116318,  841.83373606,  156.87237578,
         802.61217579,  795.96202907,  920.69045803,  621.96516752,
         659.18724769,  470.81259805,  771.32406968,  352.40325626,
         455.66972482,  234.36600888,  562.45454038,  864.83981264,
         787.19723703,  649.48042176,  902.6478154 ,  544.00539886,
        1174.78638035,  120.3598967 ,  839.61141672,  633.30453444,
        -706.66815087, -630.2039816 , -569.3451386 , -527.50996698,
        -359.53701083, -476.64334832, -411.60620464, -375.11950586,
        -345.37195689, -376.22044258, -407.31761977, -456.23251936,
        -596.86960184, -107.97072355, -394.82170044, -229.18125598,
        -288.46356547, -362.13402385, -450.87896465, -277.03932676,
        -414.99293368, -452.28771693, -167.54649092, -270.9043748 ,
        -252.20140951, -357.72497343, -259.12468742,  418.35938483,
         604.54173228,   43.10390907,  152.24258478,  378.16731033,
         416.12032881]),
 array([ 556.33985842, 

In [43]:
# now define the (f,update) tuple for optimize for logistic regression, L2
# regularization, and gradient descent
def gd_l2(y, X, lambda_):
    # YOUR CODE HERE
    def objective(w):
        p_i0 = logsigma(-np.dot(X,w))
        p_i1 = logsigma(np.dot(X,w))
        objective = -np.sum(y*p_i1 + (1-y)*p_i0)
        l2 = (lambda_/2)*(np.dot(w,w))
        return objective+l2
    def update(w,eps) :
        gradient = dl_l2(y,X,w,lambda_)
        w += eps * gradient
        return w 
    return (objective,update)

In [44]:
# let's run!
lambda_ = 100
wz_gd_l2, vz_gd_l2, ez_gd_l2 = optimize(gd_l2(y, Xz, lambda_), w0, nepochs=500)

Epoch   0: f=  5484.455, eps=0.010000000
Epoch   1: f=  2137.652, eps=0.010500000
Epoch   2: f= 30782.824, eps=0.005250000
Epoch   3: f=  6484.999, eps=0.005512500
Epoch   4: f=  1504.659, eps=0.005788125
Epoch   5: f=  1141.295, eps=0.006077531
Epoch   6: f=  1771.465, eps=0.003038766
Epoch   7: f=  1585.487, eps=0.003190704
Epoch   8: f=  1075.240, eps=0.003350239
Epoch   9: f=  1073.052, eps=0.003517751
Epoch  10: f=  1116.047, eps=0.001758876
Epoch  11: f=  1017.587, eps=0.001846819
Epoch  12: f=   990.329, eps=0.001939160
Epoch  13: f=   988.737, eps=0.002036118
Epoch  14: f=   988.563, eps=0.002137924
Epoch  15: f=   988.528, eps=0.002244820
Epoch  16: f=   988.518, eps=0.002357061
Epoch  17: f=   988.514, eps=0.002474914
Epoch  18: f=   988.513, eps=0.002598660
Epoch  19: f=   988.513, eps=0.002728593
Epoch  20: f=   988.513, eps=0.002865023
Epoch  21: f=   988.513, eps=0.001432511
Epoch  22: f=   988.512, eps=0.001504137
Epoch  23: f=   988.512, eps=0.001579344
Epoch  24: f=   

Epoch 412: f=   988.512, eps=0.000000000
Epoch 413: f=   988.512, eps=0.000000000
Epoch 414: f=   988.512, eps=0.000000000
Epoch 415: f=   988.512, eps=0.000000000
Epoch 416: f=   988.512, eps=0.000000000
Epoch 417: f=   988.512, eps=0.000000000
Epoch 418: f=   988.512, eps=0.000000000
Epoch 419: f=   988.512, eps=0.000000000
Epoch 420: f=   988.512, eps=0.000000000
Epoch 421: f=   988.512, eps=0.000000000
Epoch 422: f=   988.512, eps=0.000000000
Epoch 423: f=   988.512, eps=0.000000000
Epoch 424: f=   988.512, eps=0.000000000
Epoch 425: f=   988.512, eps=0.000000000
Epoch 426: f=   988.512, eps=0.000000000
Epoch 427: f=   988.512, eps=0.000000000
Epoch 428: f=   988.512, eps=0.000000000
Epoch 429: f=   988.512, eps=0.000000000
Epoch 430: f=   988.512, eps=0.000000000
Epoch 431: f=   988.512, eps=0.000000000
Epoch 432: f=   988.512, eps=0.000000000
Epoch 433: f=   988.512, eps=0.000000000
Epoch 434: f=   988.512, eps=0.000000000
Epoch 435: f=   988.512, eps=0.000000000
Epoch 436: f=   

## 4b Effect of Prior

In [45]:
# YOUR CODE HERE

## 4c Composition of Weight Vector

In [46]:
# YOUR CODE HERE

## 5 Exploration (optional)

### 5 Exploration: PyTorch

In [47]:
# if you want to experiment, here is an implementation of logistic
# regression in PyTorch
import math
import torch
import torch.nn as nn
import torch.utils.data
import torch.nn.functional as F

# prepare the data
Xztorch = torch.FloatTensor(Xz)
ytorch = torch.LongTensor(y)
train = torch.utils.data.TensorDataset(Xztorch, ytorch)


# manual implementation of logistic regression (without bias)
class LogisticRegression(nn.Module):
    def __init__(self, D, C):
        super(LogisticRegression, self).__init__()
        self.weights = torch.nn.Parameter(
            torch.randn(D, C) / math.sqrt(D)
        )  # xavier initialization
        self.register_parameter("W", self.weights)

    def forward(self, x):
        out = torch.matmul(x, self.weights)
        out = F.log_softmax(out)
        return out


# define the objective and update function. here we ignore the learning rates
# and parameters given to us by optimize (they are stored in the PyTorch model
# and optimizer, resp., instead)
def opt_pytorch():
    model = LogisticRegression(D, 2)
    criterion = nn.NLLLoss(reduction="sum")
    # change the next line to try different optimizers
    # optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    def objective(_):
        outputs = model(Xztorch)
        return criterion(outputs, ytorch)

    def update(_1, _2):
        for i, (examples, labels) in enumerate(train_loader):
            outputs = model(examples)
            loss = criterion(outputs, labels)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        W = model.state_dict()["W"]
        w = W[:, 1] - W[:, 0]
        return w

    return (objective, update)

In [48]:
# run the optimizer
learning_rate = 0.01
batch_size = 100  # number of data points to sample for gradient estimate
shuffle = True  # sample with replacement (false) or without replacement (true)

train_loader = torch.utils.data.DataLoader(train, batch_size, shuffle=True)
wz_t, vz_t, _ = optimize(opt_pytorch(), None, nepochs=100, eps0=None, verbose=True)

/var/folders/j5/tqm3_jyd1mz9mmb920s62hlm0000gn/T/ipykernel_31523/2194961090.py:26: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  out = F.log_softmax(out)


Epoch   0: f=  2815.387, eps=       nan
Epoch   1: f=   907.160, eps=       nan
Epoch   2: f=   791.752, eps=       nan
Epoch   3: f=   749.509, eps=       nan
Epoch   4: f=   726.905, eps=       nan
Epoch   5: f=   712.422, eps=       nan
Epoch   6: f=   700.858, eps=       nan
Epoch   7: f=   693.756, eps=       nan
Epoch   8: f=   689.438, eps=       nan
Epoch   9: f=   683.860, eps=       nan
Epoch  10: f=   680.829, eps=       nan
Epoch  11: f=   678.680, eps=       nan
Epoch  12: f=   676.080, eps=       nan
Epoch  13: f=   673.790, eps=       nan
Epoch  14: f=   672.939, eps=       nan
Epoch  15: f=   671.321, eps=       nan
Epoch  16: f=   670.018, eps=       nan
Epoch  17: f=   668.922, eps=       nan
Epoch  18: f=   668.005, eps=       nan
Epoch  19: f=   667.138, eps=       nan
Epoch  20: f=   666.417, eps=       nan
Epoch  21: f=   665.473, eps=       nan
Epoch  22: f=   664.786, eps=       nan
Epoch  23: f=   664.258, eps=       nan
Epoch  24: f=   664.024, eps=       nan
